# DevOps Profile
# Perfect for: Infrastructure engineers, SREs, Cloud architects
# Install time: ~20 minutes

name: devops
description: Infrastructure as Code and cloud management tools
author: OS Post-Install Scripts Team
version: 1.0.0

# What gets installed
packages:
  # Version Control
  version_control:
    - git
    - git-lfs
    - github-cli
    
  # Container & Orchestration
  containers:
    - docker
    - docker-compose
    - podman
    - kubectl
    - k9s
    - helm
    
  # Infrastructure as Code
  iac:
    - terraform
    - ansible
    - vagrant
    
  # Cloud CLIs
  cloud:
    - awscli
    - azure-cli
    - gcloud
    
  # Programming Languages
  languages:
    - python3
    - golang
    - nodejs
    
  # Editors
  editors:
    - vscode
    - vim
    
  # Shell Enhancement
  shell:
    - zsh
    - oh-my-zsh
    - starship
    
  # Monitoring & Debugging
  monitoring:
    - htop
    - iotop
    - nethogs
    - tcpdump
    - nmap
    
  # Development Tools
  dev_tools:
    - make
    - jq
    - yq
    - httpie
    - curl
    - tmux
    
  # Security Tools
  security:
    - openssl
    - gnupg
    - pass

# Configuration
config:
  shell:
    default: zsh
    theme: starship
    plugins:
      - kubectl
      - docker
      - terraform
      - aws
    
  git:
    setup_credentials: true
    global_gitignore: true
    
  vscode:
    install_extensions: true
    extensions:
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - hashicorp.terraform
      - redhat.ansible
      - ms-vscode-remote.remote-containers
      - ms-azuretools.vscode-docker
      
  docker:
    add_user_to_group: true
    install_compose: true

# Post-install actions
post_install:
  - message: "🚀 DevOps environment ready!"
  - show_versions: true
  - create_projects_folder: ~/Infrastructure

# System requirements
requirements:
  min_ram: 4GB
  recommended_ram: 8GB
  disk_space: 20GB