#!/usr/bin/env bash
#######################################
# Script: dotfiles-install.sh
# Description: Installs/uninstalls dotfiles symlinks
# Author: Bragatte
# Date: 2026-02-05
#######################################

# Prevent multiple sourcing
[[ -n "${_DOTFILES_INSTALL_SOURCED:-}" ]] && return 0
readonly _DOTFILES_INSTALL_SOURCED=1

# Determine paths
# NOTE: Always use BASH_SOURCE[0] for this script's location, not SCRIPT_DIR
# which may be set by the calling script (setup.sh)
_INSTALLER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "${_INSTALLER_DIR}/../.." && pwd -P)"

# Source dependencies
source "${REPO_ROOT}/src/core/logging.sh"
source "${REPO_ROOT}/src/core/dotfiles.sh"

# Dotfiles locations
DOTFILES_DATA="${REPO_ROOT}/data/dotfiles"

# Plugin locations (per CONTEXT.md: git clone to ~/.zsh/)
ZSH_PLUGINS_DIR="${HOME}/.zsh"

#######################################
# install_zsh_plugins()
# Installs essential zsh plugins via git clone
# Per CONTEXT.md: zsh-autosuggestions + zsh-syntax-highlighting
#######################################
install_zsh_plugins() {
    log_info "Installing essential zsh plugins..."

    # Create plugins directory if needed
    if [[ "${DRY_RUN:-}" == "true" ]]; then
        log_info "[DRY_RUN] Would create $ZSH_PLUGINS_DIR"
    else
        mkdir -p "$ZSH_PLUGINS_DIR"
    fi

    # Essential plugins per CONTEXT.md
    # NOTE: Using indexed array (not associative) for bash 3.2 compatibility (macOS)
    local plugins=(
        "zsh-autosuggestions https://github.com/zsh-users/zsh-autosuggestions.git"
        "zsh-syntax-highlighting https://github.com/zsh-users/zsh-syntax-highlighting.git"
    )

    for plugin_entry in "${plugins[@]}"; do
        local plugin_name="${plugin_entry%% *}"
        local plugin_url="${plugin_entry#* }"
        local plugin_path="${ZSH_PLUGINS_DIR}/${plugin_name}"

        if [[ -d "$plugin_path" ]]; then
            log_info "Plugin already installed: $plugin_name"
            continue
        fi

        if [[ "${DRY_RUN:-}" == "true" ]]; then
            log_info "[DRY_RUN] Would clone $plugin_name to $plugin_path"
        else
            log_info "Installing plugin: $plugin_name"
            if git clone --depth 1 "$plugin_url" "$plugin_path" 2>/dev/null; then
                log_ok "Installed: $plugin_name"
            else
                log_warn "Failed to install $plugin_name (git clone failed)"
            fi
        fi
    done

    log_ok "Plugin installation complete"
}

#######################################
# setup_git_user()
# Prompts for and sets git user.name and user.email in ~/.gitconfig.local
#######################################
setup_git_user() {
    local gitconfig_local="${HOME}/.gitconfig.local"

    # Skip if already configured
    if [[ -f "$gitconfig_local" ]] && grep -q '^\[user\]' "$gitconfig_local"; then
        log_info "Git user already configured in ~/.gitconfig.local"
        return 0
    fi

    # Skip if non-interactive
    if [[ ! -t 0 ]]; then
        log_warn "Non-interactive mode - skipping git user setup"
        log_info "Run 'git config --global user.name \"Your Name\"' manually"
        return 0
    fi

    log_info "Setting up git user configuration..."

    local name email

    # Prompt for name
    read -rp "Enter your git user.name: " name
    if [[ -z "$name" ]]; then
        log_warn "No name provided - skipping git user setup"
        return 0
    fi

    # Prompt for email
    read -rp "Enter your git user.email: " email
    if [[ -z "$email" ]]; then
        log_warn "No email provided - skipping git user setup"
        return 0
    fi

    # Respect DRY_RUN
    if [[ "${DRY_RUN:-}" == "true" ]]; then
        log_info "[DRY_RUN] Would create ~/.gitconfig.local with:"
        log_info "  user.name = $name"
        log_info "  user.email = $email"
        return 0
    fi

    # Write to gitconfig.local
    cat > "$gitconfig_local" << EOF
# Local git configuration
# Generated by os-postinstall-scripts

[user]
    name = $name
    email = $email
EOF

    log_ok "Created ~/.gitconfig.local with your git identity"
}

#######################################
# install_dotfiles()
# Creates symlinks for all dotfiles
#######################################
install_dotfiles() {
    log_banner "Dotfiles Installation"

    # Symlink mappings: source -> target
    # Format: "relative_path_in_data/dotfiles:target_in_HOME"
    # NOTE: create_dotfile_symlink handles mkdir -p for parent dirs (e.g., ~/.config/git/)
    local -a symlink_map=(
        "zsh/zshrc:${HOME}/.zshrc"
        "bash/bashrc:${HOME}/.bashrc"
        "git/gitconfig:${HOME}/.gitconfig"
        "git/gitignore:${HOME}/.config/git/ignore"
        "starship/starship.toml:${HOME}/.config/starship.toml"
    )

    local failed=0
    local skip_gitconfig=false

    # Safeguard: warn before replacing an existing gitconfig that isn't our symlink
    local gitconfig_target="${HOME}/.gitconfig"
    if [[ -f "$gitconfig_target" ]] && [[ ! -L "$gitconfig_target" ]]; then
        echo ""
        # shellcheck disable=SC2088
        log_warn "~/.gitconfig already exists with your git identity:"
        git config --global user.name 2>/dev/null  | xargs -I{} echo "        user.name  = {}"
        git config --global user.email 2>/dev/null | xargs -I{} echo "        user.email = {}"
        echo ""
        log_warn "Replacing it will symlink to this project's gitconfig."
        log_warn "Your user.name/email will need to be reconfigured in ~/.gitconfig.local"
        echo ""
        if [[ -t 0 ]]; then
            read -rp "$(echo -e "  ${BLUE:-}?${NC:-} Replace ~/.gitconfig? [y/N] ")" answer
            if [[ ! "$answer" =~ ^[yYsS]$ ]]; then
                log_info "Keeping your existing ~/.gitconfig"
                skip_gitconfig=true
            fi
        else
            log_info "Non-interactive mode — skipping gitconfig to protect existing config"
            skip_gitconfig=true
        fi
    fi

    for mapping in "${symlink_map[@]}"; do
        local source_rel="${mapping%%:*}"
        local target="${mapping##*:}"
        local source="${DOTFILES_DATA}/${source_rel}"

        # Skip gitconfig if user declined
        if [[ "$skip_gitconfig" == "true" ]] && [[ "$target" == "$gitconfig_target" ]]; then
            log_info "Skipped: ~/.gitconfig (preserved existing)"
            continue
        fi

        # Skip if source doesn't exist
        if [[ ! -f "$source" ]]; then
            log_warn "Source not found, skipping: $source"
            continue
        fi

        # Create symlink (function handles backup AND parent directory creation)
        if ! create_dotfile_symlink "$source" "$target"; then
            log_error "Failed to link: $target"
            ((failed++))
        fi
    done

    # Show backup summary
    show_backup_summary

    # Install essential zsh plugins
    install_zsh_plugins

    # Setup git user if gitconfig was linked
    if [[ -L "${HOME}/.gitconfig" ]]; then
        setup_git_user
    fi

    if ((failed > 0)); then
        log_error "Dotfiles installation completed with $failed errors"
        return 1
    fi

    log_ok "Dotfiles installation complete"
    return 0
}

#######################################
# remove_dotfiles()
# Removes symlinks and optionally restores backups
#######################################
remove_dotfiles() {
    log_banner "Dotfiles Removal"

    local -a targets=(
        "${HOME}/.zshrc"
        "${HOME}/.bashrc"
        "${HOME}/.gitconfig"
        "${HOME}/.config/git/ignore"
        "${HOME}/.config/starship.toml"
    )

    for target in "${targets[@]}"; do
        if [[ -L "$target" ]]; then
            unlink_dotfiles "$target"
        fi
    done

    log_ok "Dotfiles removal complete"
}

# Export functions
export -f setup_git_user install_dotfiles remove_dotfiles install_zsh_plugins
