# Data Scientist Configuration Template
# Optimized for data science and machine learning workflows

# User Configuration
user:
  name: "${USER}"
  email: "data.scientist@example.com"
  
# Feature Configuration
features:
  # Shell configuration
  shell:
    profile: "full"
    modules:
      base: true
      rust_tools: true
      conda: true          # Essential for data science
      mamba: true          # Faster conda alternative
      julia: true          # Julia language support
      git_advanced: true
      ai_tools: true
      docker: true
      python: true
      research_tools: true
      productivity: true
  
  # Development tools
  tools:
    python:
      install: true
      manager: "mamba"  # Faster than conda
      default_env: "ds-base"
      packages:
        - ipython
        - jupyter
        - jupyterlab
        - numpy
        - pandas
        - matplotlib
        - seaborn
        - scikit-learn
        - tensorflow
        - pytorch
        - xgboost
        - lightgbm
        - statsmodels
        - plotly
        - dash
        - streamlit
        - polars      # Fast dataframe library
        - dask        # Parallel computing
        - ray         # Distributed computing
    
    r:
      install: true
      packages:
        - tidyverse
        - ggplot2
        - dplyr
        - caret
        - randomForest
        - xgboost
        - shiny
        - rmarkdown
    
    julia:
      install: true
      packages:
        - DataFrames
        - Plots
        - StatsBase
        - MLJ
        - Flux
        - DifferentialEquations
    
    rust:
      install: true
      tools:
        - bat
        - eza
        - fd-find
        - ripgrep
        - tokei
        - dust
        - bottom
        - polars-cli  # Polars CLI tools

# AI/ML specific tools
ml_tools:
  frameworks:
    - tensorflow
    - pytorch
    - jax
    - scikit-learn
    - xgboost
    - lightgbm
  
  notebooks:
    - jupyter
    - jupyterlab
    - google-colab-cli
  
  visualization:
    - matplotlib
    - seaborn
    - plotly
    - bokeh
    - altair
    - holoviews
  
  experiment_tracking:
    - mlflow
    - wandb
    - tensorboard
    - dvc
  
  cloud_platforms:
    - aws-cli
    - gcloud
    - azure-cli
    - kaggle-cli

# Data engineering tools
data_engineering:
  databases:
    - postgresql-client
    - mysql-client
    - redis-cli
    - mongodb-tools
  
  big_data:
    - apache-spark
    - hadoop-client
    - kafka-tools
  
  etl_tools:
    - airflow
    - prefect
    - dagster

# Platform-specific overrides
platforms:
  macos:
    additional_tools:
      - stats      # System monitor
      - rectangle  # Window management
      - iterm2     # Better terminal
  
  linux:
    additional_tools:
      - nvidia-cuda-toolkit
      - cudnn
      - system76-cuda-pophos  # For Pop!_OS users