# DevOps Engineer Configuration Template
# Optimized for infrastructure and operations

# User Configuration
user:
  name: "${USER}"
  email: "devops@example.com"
  
# Feature Configuration
features:
  # Shell configuration
  shell:
    profile: "full"
    modules:
      base: true
      rust_tools: true
      git_advanced: true
      docker: true
      kubernetes: true
      terraform: true
      ansible: true
      aws: true
      gcp: true
      azure: true
      monitoring: true
      security: true
  
  # Development tools
  tools:
    rust:
      install: true
      tools:
        - bat
        - eza
        - fd-find
        - ripgrep
        - bottom      # System monitor
        - bandwhich   # Network monitor
        - procs       # Process viewer
        - dust        # Disk usage
        - ytop        # System monitor
        - grex        # Regex builder
    
    python:
      install: true
      packages:
        - ansible
        - awscli
        - boto3
        - terraform-compliance
        - molecule
        - pytest
        - requests
        - pyyaml
        - jinja2
    
    go:
      install: true
      packages:
        - github.com/kubernetes/kubectl
        - github.com/helm/helm
        - github.com/terraform-docs/terraform-docs
        - github.com/gruntwork-io/terragrunt
        - github.com/kubernetes-sigs/kind

# Infrastructure as Code
infrastructure:
  terraform:
    install: true
    version: "latest"
    providers:
      - aws
      - azurerm
      - google
      - kubernetes
      - helm
      - docker
    tools:
      - terragrunt
      - terraform-docs
      - tflint
      - tfsec
      - checkov
      - terrascan
  
  ansible:
    install: true
    collections:
      - community.general
      - ansible.posix
      - community.docker
      - kubernetes.core
      - amazon.aws
      - google.cloud
      - azure.azcollection
  
  pulumi:
    install: true
    languages:
      - typescript
      - python
      - go

# Container orchestration
containers:
  docker:
    install: true
    compose: true
    buildx: true
    tools:
      - dive        # Image explorer
      - hadolint    # Dockerfile linter
      - docker-slim # Image optimizer
      - ctop        # Container metrics
  
  kubernetes:
    tools:
      - kubectl
      - helm
      - kustomize
      - k9s         # Terminal UI
      - kubectx     # Context switching
      - kubens      # Namespace switching
      - stern       # Multi-pod logs
      - kubespy     # Real-time monitoring
      - kubectl-tree # Resource tree view
      - kubeseal    # Sealed secrets
      - velero      # Backup tool
      - flux        # GitOps
      - argocd      # GitOps

# Cloud platforms
cloud:
  aws:
    cli: true
    tools:
      - aws-vault
      - aws-sam-cli
      - aws-cdk
      - eksctl
      - copilot-cli
  
  gcp:
    cli: true
    tools:
      - cloud-sdk
      - gke-gcloud-auth-plugin
  
  azure:
    cli: true
    tools:
      - azure-functions-core-tools
      - azd

# Monitoring and observability
monitoring:
  metrics:
    - prometheus
    - grafana
    - alertmanager
    - node-exporter
  
  logging:
    - elasticsearch
    - logstash
    - kibana
    - fluentd
    - vector
  
  tracing:
    - jaeger
    - zipkin
    - opentelemetry
  
  apm:
    - datadog-agent
    - new-relic
    - appdynamics

# Security tools
security:
  scanning:
    - trivy       # Vulnerability scanner
    - grype       # Container scanner
    - syft        # SBOM generator
    - cosign      # Container signing
    - falco       # Runtime security
  
  secrets:
    - vault
    - sealed-secrets
    - sops
    - age
  
  compliance:
    - open-policy-agent
    - polaris
    - kubesec
    - kube-bench
    - kube-hunter

# CI/CD tools
cicd:
  - jenkins
  - gitlab-runner
  - github-actions-runner
  - circleci-cli
  - drone-cli
  - tekton-cli
  - argo-workflows

# Platform-specific overrides
platforms:
  macos:
    additional_tools:
      - lens        # Kubernetes IDE
      - multipass   # VM manager
      - orbstack    # Docker Desktop alternative
  
  linux:
    additional_tools:
      - cockpit     # Web-based server manager
      - webmin      # System administration