# Web Developer Configuration Template
# Optimized for modern web development

# User Configuration
user:
  name: "${USER}"
  email: "web.dev@example.com"
  
# Feature Configuration
features:
  # Shell configuration
  shell:
    profile: "standard"
    modules:
      base: true
      rust_tools: true
      git_advanced: true
      docker: true
      node: true
      ai_tools: true
      productivity: true
  
  # Development tools
  tools:
    node:
      install: true
      version: "lts"
      global_packages:
        - pnpm
        - yarn
        - typescript
        - ts-node
        - nodemon
        - pm2
        - serve
        - vercel
        - netlify-cli
        - create-react-app
        - create-next-app
        - vite
        - @angular/cli
        - @vue/cli
        - gatsby-cli
        - expo-cli
    
    python:
      install: true
      manager: "uv"
      packages:
        - django
        - flask
        - fastapi
        - uvicorn
        - requests
        - beautifulsoup4
        - selenium
    
    rust:
      install: true
      tools:
        - bat
        - eza
        - fd-find
        - ripgrep
        - watchexec   # File watcher
        - cargo-watch # Rust file watcher
        - wasm-pack   # WebAssembly

# Web development specific
web_development:
  frameworks:
    frontend:
      - react
      - vue
      - angular
      - svelte
      - solid
      - qwik
      - astro
    
    backend:
      - express
      - nestjs
      - fastify
      - hapi
      - koa
      - nextjs
      - remix
      - nuxt
    
    css:
      - tailwindcss
      - postcss
      - sass
      - less
      - styled-components
      - emotion
    
    build_tools:
      - webpack
      - vite
      - parcel
      - rollup
      - esbuild
      - turbopack
    
    testing:
      - jest
      - vitest
      - cypress
      - playwright
      - testing-library
      - mocha
      - chai
    
    linting:
      - eslint
      - prettier
      - stylelint
      - commitlint
      - husky
      - lint-staged

# Browser and debugging tools
browsers:
  - chrome
  - firefox
  - brave
  - edge
  
  extensions:
    - react-devtools
    - vue-devtools
    - redux-devtools
    - lighthouse
    - wappalyzer

# API development
api_tools:
  - postman
  - insomnia
  - httpie
  - curl
  - graphql-playground
  - swagger-ui

# Database tools
databases:
  - postgresql
  - mysql
  - mongodb
  - redis
  - sqlite
  
  gui_tools:
    - dbeaver
    - tableplus
    - mongodb-compass
    - redis-desktop-manager

# Deployment and CI/CD
deployment:
  platforms:
    - vercel
    - netlify
    - heroku
    - fly.io
    - railway
    - render
  
  ci_cd:
    - github-actions
    - gitlab-ci
    - circleci
    - jenkins
    - travis-ci

# Platform-specific overrides
platforms:
  macos:
    additional_tools:
      - rectangle     # Window management
      - responsively  # Responsive design testing
      - imageoptim    # Image optimization
  
  linux:
    additional_tools:
      - chromium
      - firefox-developer-edition