# Agent-OS Global Configuration

system:
  version: 1.0.0
  author: Bragatte

memory:
  dbPath: ~/.agent-os/memory/agents.db
  maxEntries: 10000
  cleanupDays: 30

hooks:
  enabled: true
  path: ~/.agent-os/hooks

agents:
  customPath: ~/.agent-os/agents
  nativePath: .claude/agents
  priority:
    - custom_override
    - native_enhanced
    - native_pure
    - custom_only

logging:
  level: info
  path: ~/.agent-os/logs
  maxSize: 10MB
  maxFiles: 5

integration:
  claude:
    enabled: true
    enhanceNativeAgents: true
    preserveNativeBehavior: true
  
  mcps:
    - sequential-thinking
    - serena
    - context7
    - fetch

templates:
  path: ~/.agent-os/templates
  defaults:
    - PRD.md
    - STORIES.md
    - ADR.md

performance:
  parallelExecution: true
  maxConcurrentAgents: 5
  cacheEnabled: true
  cacheTTL: 3600 # 1 hour in seconds

colors:
  enabled: true
  palette: ['blue', 'green', 'yellow', 'magenta', 'cyan', 'red', 'white', 'gray']
  autoAssign: true
  showEmoji: true
  themeColors:
    analyst: blue
    architect: green
    developer: yellow
    tester: magenta
    orchestrator: cyan
    debugger: red